version: "3.3"

services:

  fastapi-gnss:
    build: .
    networks:
      - proxy
      - zenoh-internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gnss.rule=Host(`app.mo.ri.se`) && PathPrefix(`/gnss`)"
      - "traefik.http.middlewares.gnss-strip-prefixes.stripprefix.prefixes=/gnss"
      - "traefik.http.routers.gnss.middlewares=gnss-strip-prefixes@docker"
      - "traefik.http.routers.gnss.entrypoints=websecure"
      - "traefik.http.routers.gnss.tls.certresolver=LEresolver"
      - "traefik.http.services.gnss.loadbalancer.server.port=8000"

networks:
  proxy:
    external: true
  zenoh-internal:
    external: true